---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resourceset-input-provider.yaml
  - resourceset.yaml
  - webhook-receiver.yaml
  - flux-webhook-ingress.yaml
  - webhook-ingress.yaml
