---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flux-operator-webhook
  namespace: flux-system
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
  labels:
    app.kubernetes.io/name: flux-operator
    app.kubernetes.io/component: webhook
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - flux-operator.homelab.haseebmajid.dev
      secretName: flux-operator-webhook-tls
  rules:
    - host: flux-operator.homelab.haseebmajid.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: flux-operator-webhook
                port:
                  number: 9443
