---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flux-operator-webhook
  namespace: flux-system
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
  labels:
    app.kubernetes.io/name: flux-operator
    app.kubernetes.io/component: webhook
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - flux-webhook.homelab.haseebmajid.dev
    secretName: flux-webhook-tls
  rules:
  - host: flux-webhook.homelab.haseebmajid.dev
    http:
      paths:
      - path: /hook
        pathType: Prefix
        backend:
          service:
            name: flux-operator-webhook
            port:
              number: 9443
      - path: /
        pathType: Prefix
        backend:
          service:
            name: flux-operator-webhook
            port:
              number: 9443
