---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release.yaml
  - vault-secret.yaml
  - connector.yaml
  # Uncomment below to enable bootstrap job for initial setup
  # - bootstrap-job.yaml
