---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helm-repository.yaml
  - rbac.yaml
  - kube-state-metrics.yaml
  - otel-agent.yaml
  - fluent-bit.yaml
