---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vault-csi-driver

resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/kubernetes-sigs/secrets-store-csi-driver/v1.3.4/deploy/secrets-store-csi-driver.yaml

# patchesStrategicMerge:
#   - vault-csi-provider-patch.yaml
