---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: openbao
  namespace: apps
resources:
  - serviceaccount.yaml
  - clusterrolebinding.yaml
commonLabels:
  app: openbao
  managed-by: flux
