---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - vault-csi-driver
  - vault-secrets-operator
  - secrets-store-csi-driver
  - gitlab-agent
  - cloudflare-tunnel
  - otel-agent
  # TODO: flux-operator - chart repository not working
  # - flux-operator
  - mirrord
  - openbao
  - tailscale
