---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gitlab-agent-k8s

resources:
  - namespace.yaml
  - helm-repository.yaml
  - vault-auth.yaml
  - vault-secret.yaml
  - helm-release.yaml
