---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - source.yaml
  - dev.yaml
  - prod.yaml
  - image-repository.yaml
  - image-policy-dev.yaml
  - image-policy-prod.yaml
  - image-update-automation.yaml
