---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflare-tunnel-config
  namespace: cloudflare-tunnel
data:
  config.yaml: |
    tunnel: k8s-gitops-tunnel
    credentials-file: /etc/cloudflared/creds/credentials.json
    ingress:
    - hostname: bugsink.haseebmajid.dev
      service: http://bugsink.prod.svc.cluster.local:8000
    - hostname: dev.banterbus.games
      service: http://banterbus.dev.svc.cluster.local:80
    - hostname: banterbus.games
      service: http://banterbus.prod.svc.cluster.local:80
    - service: http_status:404
