---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-creds
  namespace: cloudflare-tunnel
type: Opaque
data:
  credentials.json: ewogICJBY2NvdW50VGFnIjogIjJkYjYyNjMwZTEwMzJlZjNlYjY4Mjk4NzA3OGU0NzQzIiwKICAiVHVubmVsU2VjcmV0IjogIjRGb3VnZzkzU3NYaERKemdkdVpUaFhjNk5OVmZDTyIsCiAgIlR1bm5lbElEIjogIjAxYmQ4ZmZlLTg0NTEtNDdlYS1hYjAyLTA0MTQwMjFjMmNkIgp9