---
# Cloudflare Tunnel Ingress Rules Template
# 
# To add ingress rules for applications, update the HelmRelease values:
#
# Example for banterbus:
# cloudflare:
#   ingress:
#     # Banterbus dev environment
#     - hostname: "banterbus-dev.haseebmajid.dev"
#       service: "http://banterbus.dev:80"
#     # Banterbus prod environment  
#     - hostname: "banterbus.haseebmajid.dev"
#       service: "http://banterbus.prod:80"
#     # Catch-all rule - must be last
#     - service: http_status:404
#
# DNS Configuration needed:
# - Add CNAME records pointing to: 0f18d6fc-7ade-4e07-90f9-19cdd2bd3f10.cfargotunnel.com
#
# This file is for reference only and not deployed